name: Deploy

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: trigger event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: emelenthia/github-actions-test-A
          event-type: run-github-actions-test-a
