name: Deploy

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print repository_dispatch event info2
        run: |
          echo "トリガーイベント: ${{ github.event_name }}"
          echo "送信元リポジトリ: ${{ github.event.repository.full_name }}"
          echo "送信元ref: ${{ github.event.client_payload.ref }}"
          echo "送信元コミット: ${{ github.event.client_payload.sha }}"
          echo "イベントタイプ: ${{ github.event.action }}"
          echo "クライアントペイロード:"
          echo "${{ toJson(github.event.client_payload) }}"

      - uses: actions/checkout@v4

      - name: trigger event
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'emelenthia',
              repo: 'github-actions-test-A',
              event_type: 'run-github-actions-test-a-3rd'
            })
