name: Deploy

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: trigger event
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'emelenthia',
              repo: 'github-actions-test-A',
              event_type: 'run-github-actions-test-a-2nd'
            })
